version: "3.8"

services:
  frontend:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_USERNAME=neo4j
      - SPRING_NEO4J_PASSWORD=12345678
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/12345678
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
